MATERIAL_CLASS = {
    'AL창호': 'Aluminum window/door',
    '도어록': 'Door lock',
    '목제창호': 'Wooden window/door',
    '수납장': 'Storage cabinet',
    '신발장': 'Shoe cabinet',
    '붙박이장': 'Built-in wardrobe',
    '양변기': 'Toilet',
    '도배장판': 'Wallpaper & flooring',
    '주방상판': 'Kitchen countertop',
    '걸레받이': 'Baseboard',
    '페인트': 'Paint',
    '난방배관': 'Heating pipe',
    '시멘트': 'Cement',
    '문': 'Door',
    '급수/급탕배관': 'Water supply/hot water pipe',
    '바닥': 'Floor',
    '계량기': 'Meter',
    '실리콘': 'Silicone',
    '선반': 'Shelf',
    '잠금장치': 'Locking device',
    '도배지': 'Wallpaper',
    '욕실장': 'Bathroom cabinet',
    '방충망': 'Insect screen',
    '대리석': 'Marble',
    'PL창호': 'Plastic window/door',
    '보일러': 'Boiler',
    '오/배수배관': 'Drain/waste water pipe',
    '패킹': 'Gasket/Packing',
    '밸브': 'Valve',
    '현관문': 'Entrance door',
    '벽면': 'Wall',
    '강제창호': 'Steel window/door',
    '천장': 'Ceiling',
    '장판': 'Floor covering (sheet)',
    '주방가구': 'Kitchen furniture',
    '석고보드': 'Gypsum board',
    '조명기구': 'Lighting fixture',
    '우수배관': 'Rainwater pipe',
    '화장대/시스템가구': 'Dressing table / system furniture',
    '감지기': 'Detector',
    '창문': 'Window',
    '손잡이': 'Handle',
    '액세서리': 'Accessory',
    '유리': 'Glass',
    '수전': 'Faucet',
    '센서': 'Sensor',
    '싱크대': 'Sink',
    'UBR': 'Heating pipe',
    '도어클로저': 'Door closer',
    '가스경보기': 'Gas detector',
    '자동식소화기': 'Automatic fire extinguisher',
    '몰딩': 'Molding',
    '스프레이건': 'Spray gun',
    '절수형페달': 'Water-saving pedal',
    '온수분배기': 'Hot water distributor',
    '환기배관': 'Ventilation duct',
    '세면대': 'Wash basin',
    '마루': 'Wood floor',
    '타일': 'Tile',
    '렌지후드': 'Range hood',
    '벽지': 'Wallpaper',
    '거울': 'Mirror',
    '구동기': 'Actuator',
    '홈통': 'Gutter',
    '난방설비': 'Heating equipment',
    '계량기함': 'Meter box',
    '가스설비': 'Gas equipment',
    '걸쇠': 'Latch',
    '조절기': 'Regulator',
    '배수구': 'Drainage',
    '벽': 'Wall',
    '욕조': 'Bathtub',
    '콘센트': 'Socket',
    '호스': 'Hose',
    '창틀': 'Window frame',
    '유리창호': 'Glass window/door',
    '장애인시설': 'Facilities for the disabled',
    '안정기': 'Stabilizer',
    '세탁기': 'Washing machine',
    '슬라이드바': 'Slide door',
    '경첩': 'Hinge',
    '도어스토퍼': 'Door stopper',
    '수도': 'Water supply',
    '상부장': 'Upper cabinet',
    '환기설비': 'Ventilation equipment',
    '절수기': 'Water-saving faucet',
    '세제통': 'Detergent container',
    '스프링클러': 'Spring cooler',
    '하부장': 'Lower cabinet',
    '소화기': 'Fire extinguisher',
}

DEFECT_CLASS = {
    '변색': 'Discoloration',
    '도장불량': 'Painting defect',
    '손잡이불량': 'Handle defect',
    '난방불량': 'Heating defect',
    '이격': 'Separation',
    '점등불량': 'Lighting defect',
    '이음불량': 'Joint defect',
    '마감불량': 'Finishing defect',
    '오염': 'Contamination',
    '노후': 'Deterioration / Aging',
    '흠집': 'Scratch',
    '유입': 'Water infiltration',
    '균열': 'Crack',
    '단차': 'Level difference / Step',
    '파손': 'Damage / Breakage',
    '부식': 'Corrosion / Rust',
    '코킹불량': 'Caulking defect',
    '자연환기구불량': 'Natural ventilation defect',
    '점검/교체': 'Inspection / Replacement',
    '고정불량': 'Fixing defect',
    '시공불량': 'Construction defect',
    '도배불량': 'Wallpapering defect',
    '벗겨짐': 'Peeling',
    '결로': 'Condensation',
    '구멍': 'Hole',
    '함몰': 'Depression / Sinkage',
    '곰팡이': 'Mold',
    '누수': 'Water leakage',
    '줄눈탈락': 'Grout loss',
    '구배불량': 'Slope defect',
    '소음': 'Noise',
    '박리': 'Delamination',
    '잠금불량': 'Locking defect',
    '백시멘트불량': 'White cement defect',
    '찢김': 'Tear / Rip',
    '들뜸': 'Lifting / Bulging',
    '작동불량': 'Operation defect / Malfunction',
    '시트지불량': 'Wallpaper defect',
    '접착불량': 'Adhesion defect',
    '개폐불량': 'Opening/closing defect',
    '커버불량': 'Cover defect',
    '배수불량': 'Drainage defect',
    '누락': 'Missing',
    '수압불량': 'Water pressure defect',
    '설치불량': 'Installation defect',
    '역류': 'Backflow',
    '수직수평불량': 'Vertical/horizontal defect',
    '탈부착/교체': 'Removal/replacement',
    '충압불량': 'Pressure defect',
}

SPACE_CLASS = {
    '발코니': 'Balcony',
    '실외기실': 'Outdoor Unit Room',
    '발코니(주방)': 'Balcony (Kitchen side)',
    '발코니(거실)': 'Balcony (Living Room side)',
    '현관': 'Entrance',
    '전실': 'Vestibule',
    '대피소': 'Refuge Space',
    '거실': 'Living Room',
    '세탁실': 'Laundry Room',
    '드레스룸': 'Dressing Room',
    '침실3': 'Bedroom 3',
    '침실4': 'Bedroom 4',
    '보일러실': 'Boiler Room',
    '부부욕실': 'Master Bathroom',
    '공용욕실': 'Common Bathroom',
    '욕실': 'Bathroom',
    '침실2': 'Bedroom 2',
    '팬트리': 'Pantry',
    '주방': 'Kitchen',
    '침실1(안방)': 'Bedroom 1 (Master Bedroom)',
    '침실1(안방)2': 'Bedroom 1-2',
    '전체': 'Entire space'
}