# Updated name.py with data from ground_truth_mapping.json
# Generated automatically

SPACE_CLASS = {
    'MDF실': 'MDF Room',
    'P.D': 'Public Development',
    'UBR': 'Unit Bath Room',
    '감시실': 'Control Room',
    '거실': 'Living Room',
    '거실2': 'Living Room',
    '게시': 'Bulletin',
    '경로당': 'Senior Citizens\' Center',
    '경비실': 'Guardroom',
    '계단': 'Staircase',
    '계단실': 'Staircase',
    '고가수조': 'High water tank',
    '공동구': 'Shared Space',
    '공동출입구': 'Common entrance',
    '공용시설': 'Common Facilities',
    '공용욕실': 'Public Bathroom',
    '공용욕실2': 'Public Bathroom',
    '공용현관': 'Common Entrance',
    '공용화장실': 'Public Restroom',
    '관리소': 'Management Office',
    '관리시설': 'Management Facilities',
    '기계실': 'Mechanical Room',
    '녹지공간': 'Green Space',
    '놀이시설': 'Playground facilities',
    '다용도실': 'Multipurpose Room',
    '단지내도로': 'Complex Internal Road',
    '단지문주': 'Doorpost of a complex',
    '대피소': 'Shelter',
    '도서관': 'Library',
    '동현관': 'Bronze Statue Hall',
    '드레스룸': 'Dressing room',
    '발코니': 'Balcony',
    '발코니(거실)': 'Living Room Balcony',
    '발코니(주방)': 'Kitchen Balcony',
    '방재실': 'Shelter Room',
    '밸브실': 'Valve Room',
    '변전실': 'Transformer Room',
    '보일러실': 'Boiler Room',
    '보행공간/광장': 'Pedestrian Space/Plaza',
    '복도': 'Corridor',
    '부부욕실': 'Master Bathroom',
    '분리수거장': 'Recycling Center',
    '빨래방': 'Laundry Room',
    '상가': 'Commercial Space',
    '세탁실': 'Laundry Room',
    '승강기': 'Elevator',
    '승강기기계실': 'Elevator Machine Room',
    '승강장': 'Elevator lobby',
    '실외기실': 'Outdoor Unit Room',
    '알파룸': 'Alfa Room',
    '어린이집': 'Kindergarten',
    '열교환기실': 'Heat Exchanger Room',
    '오수처리시설': 'Sewage Treatment Facility',
    '옥내': 'Indoor',
    '옥상': 'Rooftop',
    '옥외/외부': 'Outdoor/Exterior',
    '외벽': 'Exterior wall',
    '외부': 'Exterior',
    '욕실': 'Bathroom',
    '우수처리시설': 'Stormwater Management Facility',
    '운동시설': 'Exercise Facility',
    '유수검지장치실': 'Rainwater Inspection Room',
    '자전거보관소': 'Bicycle Storage Room',
    '장애인경사로': 'Handicap Ramp',
    '전기실': 'Electrical Room',
    '전실': 'Living Room',
    '전체': 'Whole',
    '주민공동시설': 'Residential Community Facilities',
    '주방': 'Kitchen',
    '주차시설': 'Parking Facility',
    '지붕': 'Roof',
    '지상주차장': 'Above-ground parking lot',
    '지하': 'Basement',
    '지하저수조': 'Underground water tank',
    '지하주차장': 'Underground Parking Lot',
    '출입구': 'Entrance',
    '침실1(안방)': 'Bedroom (Master Bedroom)',
    '침실1(안방)2': 'Bedroom (Master Bedroom)',
    '침실2': 'Bedroom ',
    '침실3': 'Bedrooms',
    '침실4': 'Bedrooms',
    '통신실': 'Communication Room',
    '퇴거(부분)': 'Partial evacuation',
    '퇴거(전체)': 'Eviction (total)',
    '팬트리': 'Pantry',
    '펌프실': 'Pump Room',
    '피로티': 'Piloti',
    '현관': 'Entrance / Foyer',
    '현관창고': 'Entrance storage',
    '환경(조형)시설': 'Environmental (Sculptural) Facility',
    '휀룸': 'Humidity Room',
    '휴게시설': 'Rest facility',
}

WORK_TYPE_CLASS = {
    '건축': 'Architecture',
    '기계': 'Machinery',
    '전기': 'Electricity',
    '조경': 'Landscaping',
    '토목': 'Civil Engineering',
    '통신': 'Communication',
}

REPAIR_WORK_CLASS = {
    'UBR공사': 'UBR Construction',
    '개별보일러공사': 'Individual Boiler Installation',
    '경미보수': 'Minor Repair',
    '계량기공사': 'Metering device construction',
    '교체공사': 'Replacement Work',
    '급수/급탕배관공사': 'Water Supply/Hot Water Piping Work',
    '기계기타공사': 'Mechanical Miscellaneous Works',
    '기타': 'Miscellaneous',
    '난방배관공사': 'Heating Pipe Installation',
    '누수공사': 'Leakage repair work',
    '도배공사': 'Wallpapering work',
    '도시가스배관공사': 'Urban Gas Pipeline Construction',
    '도장공사': 'Painting Work',
    '동력설비공사': 'Power Facility Construction',
    '마감공사': 'Finishing work',
    '목공사': 'Carpentry',
    '바닥공사': 'Flooring Work',
    '방수공사': 'Waterproofing work',
    '배관/배선공사': 'Plumbing/Electrical work',
    '보수공사': 'Repair work',
    '부품교체': 'Part Replacement',
    '소방설비공사': 'Fire Protection Facilities Construction',
    '소화배관공사': 'Firefighting Piping Work',
    '수장공사': 'Plumbing work',
    '에어컨기타공사': 'Air Conditioning Miscellaneous Construction',
    '오/배수배관공사': 'Waste/Drainage Pipe Work',
    '우수배관공사': 'Drainage Pipe Work',
    '위생도기류공사': 'Sanitary ware installation',
    '유리공사': 'Glasswork',
    '자동제어공사': 'Automatic Control Work',
    '잡공사': 'Miscellaneous construction',
    '잡철공사': 'Miscellaneous Iron Works',
    '장판공사': 'Vinyl Flooring Work',
    '전면교체': 'Full Frontal Replacement',
    '정보제어, 보안설비공사': 'Information Control, Security Facilities Construction',
    '정보통신설비공사': 'Information and Communication Facilities Construction',
    '조경시설물공사': 'Landscape Facilities Construction',
    '조명설비공사': 'Lighting Installation Work',
    '중앙보일러공사': 'Central Boiler Construction',
    '창호공사': 'Window Installation Work',
    '철근콘크리트': 'Reinforced Concrete',
    '타일공사': 'Tile Work',
    '펌프류공사': 'Pump Installation Work',
    '환기공사': 'Ventilation work',
    '환기배관공사': 'Ventilation Pipe Work',
}

MATERIAL_CLASS = {
    'AL창호': 'Aluminum window / Aluminum frame window',
    'CCTV': 'CCTV',
    'CRT': 'CRT (Cathode Ray Tube)',
    'DVR': 'DVR (Digital Video Recorder)',
    '구동기': 'Actuator',
    'DVR/NVR': 'DVR / NVR',
    'PL창호': 'Plastic (PVC) window / PVC-framed window',
    'TV': 'Television / TV set',
    'TV공청설비': 'Communal TV reception system',
    'TV안테나': 'TV antenna / Television antenna',
    'UPS': 'UPS (Uninterruptible Power Supply)',
    '가로등': 'Streetlight / Street lamp',
    '가스검침': 'Gas meter reading / Gas meter inspection',
    '가스경보기': 'Gas detector / Gas alarm',
    '가스설비': 'Gas equipment / Gas installation',
    '가스원격검침': 'Remote gas metering / Remote gas reading',
    '가스쿡탑': 'Gas cooktop / Gas stove top',
    '간이그늘막': 'Temporary canopy / Shade structure',
    '간판': 'Signboard / Signage',
    '감시반': 'Monitoring panel / Surveillance control panel',
    '감지기': 'Detector / Sensor',
    '강제창호': 'Steel window / Steel-framed window',
    '거름망': 'Strainer / Filter screen',
    '거울': 'Mirror',
    '걸레받이': 'Baseboard / Skirting board',
    '걸쇠': 'Latch / Bolt',
    '경비실기': 'Security office equipment / Guardhouse equipment',
    '계량기': 'Meter (utility meter)',
    '계량기함': 'Meter box / Meter enclosure',
    '계전기': 'Relay (protective relay)',
    '고가수조': 'Elevated water tank / Overhead tank',
    '공기주입기': 'Air blower / Inflator',
    '관리소기': 'Management office equipment / Facility management equipment',
    '급수/급탕배관': 'Cold & hot water supply piping',
    '급수/급탕펌프': 'Water supply / Hot water pump',
    '급수전': 'Hydrant / Water hydrant',
    '급수펌프': 'Water supply pump',
    '급탕펌프': 'Hot water (domestic) pump',
    '기계기타': 'Other mechanical equipment / Misc mechanical parts',
    '기타부품': 'Other parts / Miscellaneous parts',
    '난간': 'Railing / Handrail / Guardrail',
    '난방배관': 'Heating piping / Heating circulation pipes',
    '난방설비': 'Heating system / Heating equipment',
    '난방순환펌프': 'Heating circulation pump',
    '녹지면(잔디면)': 'Green area (lawn surface)',
    '논슬립(계단)': 'Non-slip stair nosing / Anti-slip (stair treads)',
    '놀이기구': 'Playground equipment / Playground apparatus',
    '놀이벽/가벽': 'Play wall / Partition wall',
    '담장': 'Wall / Fence wall',
    '대리석': 'Marble (stone)',
    '도배지': 'Wallpaper / Wall covering',
    '도배장판': 'Wallpaper and Floor Covering',
    '도어락': 'Door lock (keyless/electronic door lock)',
    '도어록': 'Door lock (electronic door lock)',
    '도어스토퍼': 'Door stopper / Door stop',
    '도어클로저': 'Door closer (hydraulic door closer)',
    '동체감지기': 'Intrusion/body detector / Motion detector',
    '라디에이터': 'Radiator',
    '렌지후드': 'Range hood / Kitchen hood',
    '마감재': 'Finish material / Finishing material',
    '마루': 'Wood flooring / Hardwood floor',
    '말뚝': 'Pile / Stake',
    '매트': 'Mat / Floor mat',
    '맨홀': 'Manhole / Manhole cover',
    '모래/칩': 'Sand / Wood chips',
    '목재': 'Timber / Wood material',
    '목재데크': 'Wooden deck / Timber decking',
    '목제창호': 'Wooden window / Wood-framed window',
    '몰딩': 'Molding / Trim',
    '무인택배함': 'Unmanned parcel locker / Package delivery locker',
    '문': 'Door',
    '물놀이시설': 'Water play facility / Splash pool facility',
    '물탱크': 'Water tank / Reservoir tank',
    '미끄럼방지': 'Anti-slip treatment / Non-slip treatment',
    '바닥': 'Floor / Flooring',
    '바닥재': 'Flooring material / Floor covering',
    '바닥포장': 'Pavement / Floor paving',
    '발신기': 'Transmitter (alarm transmitter)',
    '발열선': 'Heating cable / Heat trace cable',
    '발전기': 'Generator',
    '방송설비': 'Public address (PA) system / Broadcasting equipment',
    '방송앰프': 'Broadcast amplifier / PA amplifier',
    '방충망': 'Insect Screen',
    '방열판': 'Heating panel / Heat sink',
    '방지턱': 'Speed bump / Curb / Wheel stop',
    '방화문': 'Fire door',
    '배관': 'Pipe / Piping',
    '배기팬': 'Exhaust fan',
    '배선': 'Wiring / Electrical wiring',
    '배수구': 'Drain / Floor drain',
    '배수시설': 'Drainage facility / Drainage system',
    '배수펌프': 'Drainage pump / Sewage pump',
    '배터리': 'Battery',
    '밸브': 'Valve',
    '법면/돌쌓기': 'Slope protection / Stone revetment',
    '벤치': 'Bench (outdoor)',
    '벽': 'Wall',
    '벽면': 'Wall surface / Wall',
    '벽지': 'Wallpaper',
    '변압기': 'Transformer',
    '보관소': 'Storage room / Storage facility',
    '보도블록': 'Paving block / Concrete paver',
    '보일러': 'Boiler',
    '분전반': 'Distribution panel / Electrical distribution board',
    '붙박이장': 'Built-in closet / Built-in wardrobe',
    '비디오폰': 'Video phone / Video intercom',
    '비상콜': 'Emergency call station / Emergency call button',
    '상판': 'Countertop / Worktop',
    '샤워부스': 'Shower booth / Shower cubicle',
    '석축': 'Stone retaining wall / Stone embankment',
    '선반': 'Shelf / Shelving',
    '세면대': 'Washbasin / Bathroom sink',
    '세탁기': 'Washing machine',
    '센서': 'Sensor',
    '소모품': 'Consumables / Spare consumable parts',
    '소방설비': 'Fire-fighting equipment / Fire protection system',
    '소방펌프': 'Fire pump',
    '소화기': 'Fire extinguisher',
    '소화배관': 'Fire suppression piping / Fire-fighting piping',
    '소화용품': 'Fire-fighting supplies / Fire-fighting accessories',
    '소화전': 'Fire hydrant / Hose reel',
    '소화펌프': 'Fire-fighting pump',
    '손잡이': 'Handle / Door handle / Knob',
    '수격방지기': 'Water hammer arrester / Surge arrester (plumbing)',
    '수경시설': 'Water garden / Aquatic planting facility',
    '수납장': 'Cabinet / Storage cabinet',
    '수도': 'Water supply / Tap water system',
    '수목': 'Trees / Woody plants',
    '수배전반': 'Low-voltage distribution board / Switchboard',
    '수신기': 'Receiver (signal receiver)',
    '수전': 'Faucet / Tap',
    '수전류': 'Water fixtures / Sanitary fixtures',
    '수중펌프': 'Submersible pump / Underwater pump',
    '순간온수기': 'Instantaneous water heater / Tankless water heater',
    '슁글': 'Shingle (roof shingle)',
    '스위치': 'Switch (electrical switch)',
    '스크류': 'Screw / Fastener',
    '스프링클러': 'Sprinkler (fire sprinkler)',
    '슬라이드바': 'Shower Slide Bar',
    '스피커': 'Speaker',
    '시멘트': 'Cement',
    '신발장': 'Shoe cabinet / Shoe rack',
    '실리콘': 'Silicone sealant / Silicone',
    '심장충격기': 'Automated External Defibrillator (AED)',
    '심장충격기 배터리': 'AED battery / Defibrillator battery',
    '심장충격기패드': 'AED pads / Defibrillator pads',
    '싱크대': 'Kitchen sink',
    '안내시설': 'Signage / Information facilities',
    '앉음벽': 'Seating wall / Low sitting wall',
    '압력탱크': 'Pressure tank',
    '액세서리': 'Accessories / Fittings',
    '양변기': 'Toilet (water closet)',
    '양변기부속': 'Toilet fittings / Toilet accessories',
    '에어컨': 'Air conditioner (A/C)',
    '연결단자': 'Terminal connector / Connection terminal',
    '연료통': 'Fuel tank',
    '열교환기': 'Heat exchanger',
    '열쇠고리': 'Key ring / Key fob',
    '예비펌프': 'Standby pump / Backup pump',
    '오/배수배관': 'Water supply & drainage pipes',
    '옹벽': 'Retaining wall',
    '온수분배기': 'Hot Water Distributor',
    '외벽': 'Exterior wall / Outer wall',
    '욕실배기팬': 'Bathroom exhaust fan',
    '욕실장': 'Bathroom cabinet / Vanity cabinet',
    '욕조': 'Bathtub',
    '운동기구': 'Exercise equipment / Fitness equipment',
    '울타리': 'Fence',
    '울타리류': 'Fencing / Types of fences',
    '우수배관': 'Rainwater Pipe',
    '원격검침': 'Remote metering / Remote metering system',
    '월패드': 'Wall pad / Home control wall pad',
    '유도등': 'Emergency/exit light / Guiding light',
    '유리': 'Glass / Glazing',
    '유리창호': 'Glazed window / Window glazing',
    '음식물탈수기': 'Food waste dehydrator / Food waste dewatering machine',
    '인터폰': 'Intercom / Video intercom',
    '입구': 'Entrance / Entryway',
    '자동제어': 'Automatic control system / Automation control',
    '자전거보관소': 'Bicycle parking / Bike rack shelter',
    '잔디': 'Grass / Lawn',
    '잔디보호매트': 'Grass protection mat / Turf protection mat',
    '잠금장치': 'Locking Device',
    '장애인시설': 'Accessibility Facility',
    '장판': 'Sheet vinyl flooring / Vinyl flooring',
    '전기실기': 'Electrical room equipment / Electrical room devices',
    '전화기': 'Telephone',
    '전환개폐기': 'Transfer switch / Changeover switch',
    '절수형페달': 'Water-saving pedal (pedal-operated faucet)',
    '점검구': 'Inspection opening / Access panel',
    '정류기': 'Rectifier',
    '정자': 'Gazebo / Pavilion',
    '제어반': 'Control panel / Control cabinet',
    '제연댐퍼': 'Smoke-control damper / Smoke damper',
    '조경수': 'Ornamental trees / Landscaping trees',
    '조명기구': 'Lighting fixture / Light fixture',
    '조절기': 'Controller / Regulator',
    '주방TV': 'Kitchen TV',
    '주방가구': 'Kitchen cabinets / Kitchen furniture',
    '주방상판': 'Kitchen Countertop',
    '중계기': 'Repeater / Signal repeater',
    '증폭기': 'Amplifier (signal amplifier)',
    '지붕': 'Roof',
    '지시계': 'Gauge / Indicator',
    '지하저수조': 'Underground reservoir / Underground storage tank',
    '차단기': 'Circuit breaker',
    '차도': 'Roadway / Driveway',
    '차량통제시스템': 'Vehicle access control system',
    '차압유량조절밸브': 'Differential pressure / Flow control valve',
    '창문': 'Window',
    '창틀': 'Window frame / Sash',
    '천장': 'Ceiling',
    '체육시설물': 'Sports facilities / Exercise equipment',
    '초인종': 'Doorbell',
    '초화류': 'Flowering plants / Herbaceous plants',
    '축전지': 'Battery bank / Storage battery',
    '충압펌프': 'Pressure boosting pump / Pressure pump',
    '커버': 'Cover / Protective cover',
    '컴퓨터': 'Computer / PC',
    '콘덴서': 'Capacitor / Condenser',
    '콘센트': 'Electrical outlet / Power outlet',
    '콘크리트': 'Concrete',
    '타이머': 'Timer',
    '타일': 'Tile',
    '탄성포장재': 'Elastic (resilient) surfacing / Rubberized surfacing',
    '태양광설비': 'Solar power system / Photovoltaic system',
    '테이블': 'Table',
    '통신기타': 'Other communications equipment / Comms miscellaneous',
    '통신단자함': 'Communication junction box / Telecom junction box',
    '통신콘센트': 'Communication outlet / Data/phone outlet',
    '통행차단시설': 'Traffic barrier / Access control barrier',
    '트렌치': 'Trench / Trench drain',
    '하부장': 'Lower Cabinet',
    '파고라': 'Pergola',
    '패킹': 'Packing / Gasket / Seal',
    '팽창탱크': 'Expansion tank',
    '펌프': 'Pump',
    '페인트': 'Paint / Coating',
    '플로어신지': 'Floor hinge / Floor-mounted door hinge',
    '피뢰설비': 'Lightning protection system / Lightning arrestor',
    '현수막거치대': 'Banner frame / Banner stand',
    '현관문': 'Entrance Door',
    '홈넷서버': 'Home network server / HomeNet server',
    '호스': 'Hose',
    '홈통': 'Gutter / Downspout',
    '화단': 'Flower bed / Planting bed',
    '화면': 'Display / Screen',
    '화재감지기': 'Fire detector / Smoke detector',
    '화재경보기': 'Fire alarm / Fire buzzer',
    '화재수신반': 'Fire alarm control panel',
    '환기배관': 'Ventilation duct / Ventilation piping',
    '환기설비': 'Ventilation system / Ventilation equipment',
    '환풍기': 'Ventilator / Exhaust fan',
    '흡출기': 'Extractor / Exhaust extractor',
    '히터': 'Heater',
}

DEFECT_CLASS = {
    '가스누설': 'Gas Leak',
    '가스누출': 'Gas Leak',
    '개폐불량': 'Opening/Closing Failure',
    '건축폐기물': 'Construction waste',
    '검침상이': 'Tilted or Leaning',
    '결로': 'Condensation',
    '결속재미제거': 'Removal of Binding Agents',
    '경계재불량': 'Lightweight Material Defect',
    '경화': 'Hardening',
    '고사': 'Deterioration',
    '고장': 'Breakdown / Fault',
    '고정불량': 'Loose fixture / Poor fastening',
    '곰팡이': 'Mold / Mildew',
    '구멍': 'Hole / Puncture',
    '구배불량': 'Improper Slope / Gradient',
    '규격미달': 'Non-compliance with standards',
    '균열': 'Crack',
    '그을림': 'Scorching',
    '긁힘': 'Scratch',
    '급수공급불량': 'Poor Water Supply',
    '긴결재미제거': 'Removal of Longitudinal Cracks',
    '난방불량': 'Heating Failure',
    '내구연한경과': 'Durability lifespan elapsed',
    '노후': 'Aging',
    '녹물': 'Rust',
    '녹발생': 'Rust occurrence',
    '누락': 'Omission / Missing Item',
    '누수': 'Water Leak',
    '누유': 'Leakage',
    '누전': 'Electrical Leakage',
    '단선': 'Disconnected Wire',
    '단전': 'Power outage',
    '단차': 'Uneven Level / Step',
    '덮개간격과다': 'Excessive Cover Spacing',
    '덮개망설치': 'Cover Net Installation',
    '도배불량': 'Poor wallpapering',
    '도장불량': 'Poor paintwork',
    '돌출': 'Protrusion',
    '동선추가/연결': 'Additional/Connected Pathway',
    '뒤틀림': 'Twisting',
    '들뜸': 'Lifting / Peeling',
    '마감불량': 'Poor Finishing',
    '마구리불량': 'Poor Edge Finishing',
    '마모': 'Wear and Tear',
    '막힘': 'Clogging / Blockage',
    '면불량': 'Uneven Surface',
    '목재썩음': 'Wood Rot',
    '무너짐': 'Collapse',
    '물고임': 'Water Pooling',
    '미설치': 'Not Installed',
    '미장누락': 'Omission of Plastering',
    '박리': 'Delamination / Flaking',
    '방수불량': 'Waterproofing Failure',
    '방전': 'Discharge',
    '배수불량': 'Poor Drainage',
    '백시멘트불량': 'White Cement Defect',
    '법면/돌쌓기하자': 'Stone Wall/Retaining Wall Defects',
    '벗겨짐': 'Peeling',
    '벨브불량': 'Valve Defect',
    '벽돌불량': 'Brick Defect',
    '변색': 'Discoloration',
    '변형': 'Deformation / Warping',
    '병충해발생': 'Pest Infestation',
    '복합하자': 'Composite Defect',
    '부식': 'Corrosion / Rust',
    '분실': 'Loss',
    '뿜칠하자': 'Blowhole defect',
    '사용': 'Usage',
    '사인불량': 'Signage Defect',
    '설비계통불량': 'Facility System Defect',
    '설치불량': 'Poor Installation',
    '센서고장': 'Sensor Malfunction',
    '소음': 'Excessive noise / Unusual noise',
    '손잡이미설치': 'Handle Not Installed',
    '손잡이불량': 'Handle Defect',
    '수압불량': 'Low Water Pressure',
    '수직불량': 'Vertical Defect',
    '수직수평불량': 'Not Plumb/Level',
    '수평불량': 'Horizontal Defect',
    '시공불량': 'Defective Construction',
    '시설/부속추가': 'Facility/Addition',
    '시트지불량': 'Sheet Defect',
    '식재불일치': 'Mismatch in Finishing Materials',
    '신규(추가)설치': 'New (Additional) Installation',
    '신축줄눈': 'Shrinkage crack',
    '실리콘불량': 'Silicone Defect',
    '썩음': 'Decay',
    '악취': 'Foul odor',
    '에폭시하자': 'Epoxy Defect',
    '역류': 'Backflow',
    '영상불량': 'Video Failure',
    '오염': 'Stain / Contamination',
    '외단열불량': 'External Insulation Defect',
    '유압불량': 'Hydraulic Deficiency',
    '유입': 'Infiltration',
    '유효기간경과': 'Expiration of Validity Period',
    '음향불량': 'Poor Acoustics',
    '이격': 'Gap / Separation',
    '이음불량': 'Poor Joint / Seam',
    '일조권침해': 'Infringement of sunlight rights',
    '자연환기구불량': 'Natural Ventilation Defect',
    '작동불량': 'Malfunction / Operation failure',
    '잠금불량': 'Locking Failure',
    '재고부족': 'Stock shortage',
    '전기시설불량': 'Electrical Facility Defect',
    '전원불량': 'Power Failure',
    '전정': 'Settlement',
    '점검/교체': 'Inspection/Replacement',
    '점등불량': 'Lighting Failure',
    '접착불량': 'Poor adhesion',
    '접촉불량': 'Poor electrical contact / Intermittent contact',
    '제어불량': 'Control Deficiency',
    '조도불량': 'Poor Illumination',
    '줄눈탈락': 'Grout Loss',
    '지하수용출': 'Groundwater seepage',
    '찢김': 'Tear',
    '철거': 'Demolition / Removal',
    '충압불량': 'Poor Compaction',
    '침수': 'Flooding',
    '침하': 'Settlement',
    '커버불량': 'Cover Defect',
    '코킹불량': 'Poor Caulking',
    '콘크리트균열': 'Concrete Cracking',
    '콘크리트면배수불량': 'Concrete Surface Drainage Deficiency',
    '콘크리트철근노출': 'Concrete Reinforcement Exposure',
    '쿠킹불량': 'Poor caulking',
    '타일불량': 'Tile Defect',
    '타일파손': 'Tile Damage',
    '탈락': 'Peeling',
    '탈부착/교체': 'Detachment/Replacement',
    '터치불량': 'Touch Screen Failure',
    '토사유실': 'Soil loss',
    '통신불량': 'Communication Failure',
    '통행방해': 'Obstruction of passage',
    '파손': 'Damage / Breakage',
    '포장불량': 'Poor Packaging',
    '표면요철': 'Surface corrugation',
    '함몰': 'Sinking / Indentation',
    '화재/침수': 'Fire/Flooding',
    '흠집': 'Scratch / Nick / Dent',
}

